version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/app/main.py
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./data/matchday.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

